building:
  trigger:
    project: sample-apps/blank-java

# parent .gitlab-ci.yml
sample_apps.blank_java:
  trigger:
    include: 
      - project: 'sample-apps/blank-java'
        file: sample-apps/blank-java/.gitlab-ci.yml

