listing_parent:
  script:
    - ls
    - echo $CI_PROJECT_DIR

building_blank_java:
  trigger: 
    include: sample-apps/blank-java/.gitlab-ci.yml
    strategy: depend
  # only:
    # changes:
    # - sample-apps/blank-java/**/*

