# building:
  # trigger:
    # project: sample-apps/blank-java

production:
  script:
    - ls

# parent .gitlab-ci.yml
sample_apps.blank_java:
  trigger:
    include: 
      - project: 'sample-apps/blank-java'
        file: .gitlab-ci.yml

