version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - cd sample-apps/java-events
      #- ./4-cleanup.sh
      - sh 4-cleanup.sh
      - 1-create-bucket.sh
      - 2-deploy.sh mvn
      - 3-invoke.sh
      - 4-cleanup.sh
  post_build:
    commands:
      - echo Build completed on `date`

