version: 0.2

env:
  shell: bash
  # ok
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - cd sample-apps/java-events
      - echo CREATING BUCKET ......... on `date`
      - bash 1-create-bucket.sh
      - echo BUILDING AND DEPLOYING.........  on `date`
      - bash 2-deploy.sh mvn
      - echo TESTING......... on `date`
      - bash 3-invoke.sh
      - echo CLEANING UP........ on `date`
      - bash 4-cleanup.sh
  post_build:
    commands:
      - echo Build completed on `date`

