version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - cd sample-apps/java-events
      #- ./4-cleanup.sh
      - bash 4-cleanup.sh
      - bash 1-create-bucket.sh
      - bash 2-deploy.sh mvn
      - bash 3-invoke.sh
      - bash 4-cleanup.sh
  post_build:
    commands:
      - echo Build completed on `date`

