variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

image: maven:3.3.9-jdk-8 #softinstigate/maven-aws #maven:3.3.9-jdk-8
#image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest  # see the note below
#image: softinstigate/maven-aws

cache:
  paths:
    - .m2/repository

    
.java-blank:
    before_script:
        - ls
        - cd sample-apps/blank-java
    after_script:
        - cd sample-apps/blank-java
        - ls 
        - ls ./target/*

# list:
  # extends: .java-blank
  # script:
    # - ls


stages:
  - build
  - deploy
  - test
  - destroy
  
build_phase:
  extends: .java-blank
  #image: maven:3.3.9-jdk-8 
  stage: build
  script:
    - ls
    - chmod 777 ./0-build.sh
    - ./0-build.sh
  artifacts:
    expire_in: 5 min
    paths: 
      - target/*.jar


deploy_phase:
  extends: .java-blank
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest  # see the note below
  stage: deploy
  script:
    - ls
    - ./1-create-bucket.sh
    - ./3-deploy.sh none
  artifacts:
    expire_in: 5 min
    paths: 
      - target/*.jar


test_phase:
  extends: .java-blank
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest  # see the note below
  stage: test
  script:
    - ./4-invoke.sh

destroy_phase:
  extends: .java-blank
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest  # see the note below
  stage: destroy
  script:
    - ./5-cleanup.sh
  when: manual

cleanup_phase:
  extends: .java-blank
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest  # see the note below
  stage: test
  script:
    - ./5-cleanup.sh
  when: on_failure
